swagger: "2.0"
info:
  title: Active Alarms List (AAL)
  description: AAL takes care of alarm state management & also provide simple rest interfaces for retrieving active alarm(s).
  version: "1.0.0"

basePath: /api/aal
schemes:
- http

paths:
  /v1/alarms:
    get:
      summary: Gets all active alarms in the system
      tags:
        - active-alarms-list
      parameters:
        - in: query
          name: integratedId
          type: string
          required: false
          description: Encoded integrated identifier.
      produces:
      - application/json
      description: |
        Get list with all presently active alarms. If integrated id is passed as query parameter, then it gets all active alarms in the system for the NEs managed by the given agent identifier.
        If integrated id is passed as query parameter, then it gets all active alarms in the system of the NE having the specified integrated identifier.

        For example:
        ```
        GET /api/aal/v1/alarms
        GET /api/aal/v1/alarms?integratedId=<integrated-identifier>
        ```

        Returns list of active alarms:
        ```
        [
          {
              "dn": "PLMN-PLMN/BSC-1",
              "systemAlarmId": "12341"
              "integratedId": "PLMN-PLMN/OMS-1"
              ...
              ...
          },
          {
              "dn": "PLMN-PLMN/BSC-2",
              "systemAlarmId": "12342"
              "integratedId": "PLMN-PLMN/OMS-1"
              ...
              ...
          },
          ...
          ...
        ]
        ```
      responses:
        '200':
          description: Fetching of all active alarms is successful.
          schema:
            $ref: "#/definitions/Alarms"
        '404':
          description: Alarms for the specified integratedId was not found.
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: Internal server error (e.g. lost database connection)
          schema:
            $ref: "#/definitions/Error"

    delete:
      summary: Deletes alarms by integrated id
      tags:
        - active-alarms-list
      parameters:
        - in: query
          name: isActive
          type: boolean
          required: true
          description: "If false, delete only inactive alarms. NOTE: Currently this has to be false, other options are not implemented."
        - in: query
          name: integratedId
          type: string
          required: true
          description: Match alarms with this integrated id
      produces:
      - application/json
      description: |
        Delete alarms by integratedId. Currently only deleting inactive alarms is supported.

        Usage:
        ```
        DELETE /api/aal/v1/alarms?isActive=false&integratedid=<integrated-id>
        ```
      responses:
        '200':
          description: Successfully deleted all alarms matching the criteria
        '500':
          description: Internal server error (e.g. lost database connection)
          schema:
            $ref: "#/definitions/Error"

  /v2/alarms:
    get:
      summary: Gets all active alarms in the system in Pages
      tags:
        - active-alarms-list
      parameters:
        - in: query
          name: next
          type: string
          required: false
          description: Encoded next page identifier.
        - in: query
          name: size
          type: string
          required: false
          description: Page size.
        - in: query
          name: integratedId
          type: string
          required: false
          description: Encoded integrated identifier.
      produces:
      - application/json
      description: |
        Get list with all presently active alarms in Pages

        For example:
        ```
        GET /api/aal/v2/alarms?size=10
        GET /api/aal/v1/alarms?integratedId=<integrated-identifier>&size=10
        ```

        Returns the first page of active alarms in chunks of 10 alarms per page:
        ```
        {
         alarms: [
                 {
                  "systemAlarmId": string,
                  "dn": string
                  ...
                  ...
                 },
                 {
                  "systemAlarmId": string,
                  "dn": string
                  ...
          .       ...
                 },
                 ...
                 ...
                 ],
         "next": "/api/aal/v2/alarms?next=ads243edccvfr3rfvbgtr&size=10"
        ]
        ```

        ```
        GET /api/aal/v2/alarms?next=ads243edccvfr3rfvbgtr&size=10
        ```

        Returns the next page of active alarms in chunks of 10 alarms per page. Empty attribute value of "next" indicates the page
        as last page to the client.
      responses:
        '200':
          description: Fetching of active alarms for the page is successful.
          schema:
            $ref: "#/definitions/PagedAlarm"
        '500':
          description: Internal server error (e.g. lost database connection)
          schema:
            $ref: "#/definitions/Error"

  /v1/alarm/{dn}/{systemAlarmId}:
    get:
      summary: Get an active alarm by key
      tags:
        - active-alarms-list
      parameters:
        - in: path
          name: dn
          type: string
          required: true
          description: Encoded distinguished name of the alarm.
        - in: path
          name: systemAlarmId
          type: string
          required: true
          description: System alarm identifier of the alarm.
      produces:
      - application/json
      description: |
        Get an active alarm by key

        For example:
        ```
        GET /api/aal/v1/alarm/PLMN-PLMN%2FBSC-1/12347
        ```

        Returns an active alarm for a given alarm distinguished name and system alarm identifier:
        ```
        {
            "dn": "PLMN-PLMN/BSC-1",
            "systemAlarmId": "12347"
            ...
            ...
        }
        ```
      responses:
        '200':
          description: Fetching of an active alarm for the given dn and system alarm id is successful.
          schema:
            $ref: "#/definitions/Alarm"
        '404':
          description: Alarms for the specified dn and system alarm id was not found.
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: Internal server error (e.g. lost database connection)
          schema:
            $ref: "#/definitions/Error"

definitions:
  Alarm:
    type: object
    description: An alarm
    required:
      - specificProblem
      - systemAlarmId
      - dn
      - integratedId
      - firstNotificationTime
      - lastUpdateNotificationTime
      - ackTime
      - clearTime
      - alarmType
      - probableCause
      - alarmText
      - severity
      - ackStatus
      - ackUser
      - clearUser
      - additionalAlarmText1
      - additionalAlarmText2
      - additionalAlarmText3
      - additionalAlarmText4
      - additionalAlarmText5
      - additionalAlarmText6
      - additionalAlarmText7
      - systemDN
    properties:
      specificProblem:
        type: string
        description: Specific problem of the alarm
        x-go-custom-tag: db:"specific_problems"
      systemAlarmId:
        type: string
        description: System alarm id
        x-go-custom-tag: db:"system_alarm_id"
      dn:
        type: string
        description: alarm dn
        x-go-custom-tag: db:"dn"
      integratedId:
        type: string
        description: Integrated id
        x-go-custom-tag: db:"integrated_id"
      firstNotificationTime:
        type: string
        description: First notification time
        x-go-custom-tag: db:"first_notification_time"
      lastUpdateNotificationTime:
        type: string
        description: Last update notification time
        x-go-custom-tag: db:"last_update_notification_time"
      ackTime:
        type: string
        description: Alarm acknowledgement time
        x-go-custom-tag: db:"ack_time"
      clearTime:
        type: string
        description: Alarm clearance time
        x-go-custom-tag: db:"clear_time"
      alarmType:
        type: string
        description: Alarm type
        x-go-custom-tag: db:"alarm_type"
      probableCause:
        type: string
        description: Probable cause of the alarm
        x-go-custom-tag: db:"probable_cause"
      alarmText:
        type: string
        description: Alarm text
        x-go-custom-tag: db:"alarm_text"
      severity:
        type: string
        description: Alarm severity
        x-go-custom-tag: db:"severity"
      ackStatus:
        type: string
        description: Alarm acknowledgement status
        x-go-custom-tag: db:"ack_status"
      ackUser:
        type: string
        description: Alarm acknowledgement user
        x-go-custom-tag: db:"ack_user"
      clearUser:
        type: string
        description: Alarm clearance user
        x-go-custom-tag: db:"clear_user"
      additionalAlarmText1:
        type: string
        description: Alarm additional text 1
        x-go-custom-tag: db:"additional_alarm_text_1"
      additionalAlarmText2:
        type: string
        description: Alarm additional text 2
        x-go-custom-tag: db:"additional_alarm_text_2"
      additionalAlarmText3:
        type: string
        description: Alarm additional text 3
        x-go-custom-tag: db:"additional_alarm_text_3"
      additionalAlarmText4:
        type: string
        description: Alarm additional text 4
        x-go-custom-tag: db:"additional_alarm_text_4"
      additionalAlarmText5:
        type: string
        description: Alarm additional text 5
        x-go-custom-tag: db:"additional_alarm_text_5"
      additionalAlarmText6:
        type: string
        description: Alarm additional text 6
        x-go-custom-tag: db:"additional_alarm_text_6"
      additionalAlarmText7:
        type: string
        description: Alarm additional text 7
        x-go-custom-tag: db:"additional_alarm_text_7"
      systemDN:
        type: string
        description: System DN
        x-go-custom-tag: db:"system_dn"
      alarmStatus:
        type: string
        description: Alarm State
      isInternal:
        type: string
        description: Indicates whether the alarm is an neo internal alarm or not. Possible values are "true" or "false".
  Alarms:
    type: array
    description: Array of alarm
    items:
      $ref: "#/definitions/Alarm"
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string
  PagedAlarm:
    type: object
    required:
      - alarms
      - next
    description: Obect indicating a page consisting of alarms.
    properties:
      alarms:
        type: array
        description: Array of alarm
        items:
          $ref: "#/definitions/Alarm"
      next:
        type: string
        description: Next page identifier