swagger: "2.0"
info:
  title: Album
  description: Album API creates/deletes/displays albums and images in the albums, making use of REST APIs and persistent storage..
  version: "1.0.0"

basePath: /
schemes:
- http

paths:
  /:
    get:
      summary: Displays the list of albums.
      produces:
      - application/json
      responses:
        '200':
          description: Fetching list of albums is successful.
          
  /{albumname}:  
    post:
      summary: Creates a specified album. 
      parameters: 
        - in: path
          name: albumname
          type: string
          required: true
          description: Name of the album to be created
      produces:
      - application/json
      responses:
        '200':
          description: Specified album created
    
    delete:
      summary: Deletes specified album.
      parameters: 
        - in: path
          name: albumname
          type: string
          required: true
          description: Name of the album to be deleted
      produces:
      - application/json
      responses:
        '200':
          description: Successfully deleted the specified album.
          
    get:
      summary: Displays all the images in the specified album
      parameters: 
        - in: path
          name: albumname
          type: string
          required: true
          description: Name of the album under which all images should be displayed
      produces:
      - application/json
      responses:
        '200':
          description: Fetching list of images in an album is successful.
          

  /{albumname}/{imagename}:
    post:
      summary: Creates a new image in the specified album.
      parameters: 
        - in: path
          name: albumname
          type: string
          required: true
          description: Name of the album under which image to be created
        - in: path
          name: imagename
          type: string
          required: true
          description: Name of the image to be created
      produces:
      - application/json
      responses:
        '200':
          description: New image created in specified album.
    
    delete:
      summary: Deletes a specified image in a specified album. 
      parameters: 
        - in: path
          name: albumname
          type: string
          required: true
          description: Name of the album under which image to be deleted
        - in: path
          name: imagename
          type: string
          required: true
          description: Name of the image to be deleted
      produces:
      - application/json
      responses:
        '200':
          description: Specified image deleted in the specified album.
    
    get:
      summary: Displays a specified image in a specified album. 
      parameters: 
        - in: path
          name: albumname
          type: string
          required: true
          description: Name of the album under which image to be displayed
        - in: path
          name: imagename
          type: string
          required: true
          description: Name of the image to be displayed
      produces:
      - application/json
      responses:
        '200':
          description: Fetching specified image in the specified album successful.
          

